image: docker:24.0.6
services:
  - docker:24.0.6-dind

stages:
  - build
  - test
  - release

variables:
  CONTAINER_REGISTRY: registry.gitlab.kuleuven.be 
  CONTAINER_TEST_IMAGE: $CONTAINER_REGISTRY/u0165022/riscv-ci-env:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CONTAINER_REGISTRY/u0165022/riscv-ci-env:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.kuleuven.be 

after_script:
 - docker logout $CONTAINER_REGISTRY


build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

spike:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE 'spike -h'

release:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main
