name: Publish docker container images

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    branches: [ '*' ]

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  

      - name: Set environment vars
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Set up BuildKit Docker container builder to be able to build multi-platform images and export cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: make build
        
      - name: Push images
        if: startsWith(github.event.ref, 'refs/tags/v') && (github.event_name != 'pull_request')
        run: make release VERSION=${{ env.VERSION }} REGISTRY=${{ env.REGISTRY }}/${{ env.REPOSITORY }}